modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "vrapi"
version = "${version}"
displayName = "mc-vr-api"
authors = "hammy3502"
description = '''
VR API mod that allows mods to integrate into Vivecraft.
'''
displayTest = "NONE"
#logoFile = ""

[[dependencies.vrapi]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"