modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "vrapi"
version = "${version}"
displayName = "mc-vr-api"
authors = "hammy3502"
description = '''
VR API mod that allows mods to integrate into Vivecraft.
'''
displayTest = "NONE"
#logoFile = ""

[[dependencies.vrapi]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.20-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.20.6]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "architectury"
type = "required"
versionRange = "[12.0.27,)"
ordering = "AFTER"
side = "BOTH"